name: Java Backend CI

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: Implementacao/backEnd/moedaestudantil-api
        run: mvn -B clean verify

      - name: Run tests
        working-directory: Implementacao/backEnd/moedaestudantil-api
        run: mvn test

      - name: Check code style (optional)
        working-directory: Implementacao/backEnd/moedaestudantil-api
        run: mvn checkstyle:check || echo "Checkstyle violations found"

      - name: Use production properties on main branch
        if: github.ref == 'refs/heads/main'
        working-directory: Implementacao/backEnd/moedaestudantil-api/src/main/resources
        run: cp application-prod.properties application.properties

      - name: Build JAR
        working-directory: Implementacao/backEnd/moedaestudantil-api
        run: mvn package -DskipTests

      - name: Build Docker image
        working-directory: Implementacao/backEnd/moedaestudantil-api
        run: docker build -t moedaestudantil-api:latest .

      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Tag Docker image for GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/moedaestudantil-api
          docker tag moedaestudantil-api:latest $IMAGE_ID:latest

      - name: Push Docker image to GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/moedaestudantil-api
          docker push $IMAGE_ID:latest
