name: Java Backend CI

on:
  push:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if relevant files changed
        id: changes
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }} | grep -E '^(Implementacao/backEnd/moedaestudantil-api/|\.github/workflows/backend\.yml)')
          if [ -z "$CHANGED" ]; then
            echo "No relevant changes detected. Skipping build."
            exit 78
          fi

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        working-directory: Implementacao/backEnd/moedaestudantil-api
        run: mvn -B clean verify

      - name: Run tests
        working-directory: Implementacao/backEnd/moedaestudantil-api
        run: mvn test

      - name: Check code style (optional)
        working-directory: Implementacao/backEnd/moedaestudantil-api
        run: mvn checkstyle:check || echo "Checkstyle violations found"

      - name: Package application
        working-directory: Implementacao/backEnd/moedaestudantil-api
        run: mvn package -DskipTests
