name: Angular CI

on:
  push:
    paths:
      - "Implementacao/moedas-ui/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    paths:
      - "Implementacao/moedas-ui/**"
      - ".github/workflows/frontend.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci --force
        working-directory: Implementacao/moedas-ui

      - name: Run tests
        run: npm run prettier-check
        working-directory: Implementacao/moedas-ui

      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
        working-directory: Implementacao/moedas-ui

      - name: Build
        run: npm run build -- --base-href /Sistema_de_Moeda_Estudantil/
        working-directory: Implementacao/moedas-ui

      - name: Set up Git user
        run: |
          git config --global user.name "gustavoevf"
          git config --global user.email "gustavoevf@gmail.com"
        working-directory: Implementacao/moedas-ui

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy -- --no-silent
        working-directory: Implementacao/moedas-ui

  create_pull_request:
    name: "Create PR"
    if: github.ref == 'refs/heads/beta'
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      pull-requests: write
    steps:
      - name: "Create PR"
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const pulls = await github.rest.pulls.list({
              owner: owner,
              repo: repo,
              head: context.ref,
              base: 'main',
              state: 'open',
            });

            if (pulls.data.length < 1) {
              await github.rest.pulls.create({
                title: '[CI] Merge beta into main',
                owner: owner,
                repo: repo,
                head: context.ref,
                base: 'main',
                body: [
                  'This PR is auto-generated by',
                  '[actions/github-script](https://github.com/actions/github-script)',
                ].join('\n'),
              });
            } else {
              const existingPR = pulls.data[0];
              await github.rest.pulls.update({
                owner: owner,
                repo: repo,
                pull_number: existingPR.number,
                body: [
                  existingPR.body,
                  `Updated by Job ${context.job}`,
                ].join('\n'),
              });
            }
